/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#819986",
        "on-error-container": "#93000a",
        "surface": "#fafaf5",
        "on-primary-fixed": "#0b2013",
        "inverse-on-surface": "#f1f1ec",
        "surface-bright": "#fafaf5",
        "on-tertiary-container": "#7b9f00",
        "on-tertiary-fixed": "#151f00",
        "on-background": "#1a1c19",
        "surface-variant": "#e3e3de",
        "on-tertiary-fixed-variant": "#3a4d00",
        "primary-fixed": "#d0e9d4",
        "on-surface": "#1a1c19",
        "surface-dim": "#dadad5",
        "surface-container-highest": "#e3e3de",
        "on-primary-fixed-variant": "#364c3c",
        "inverse-primary": "#b4cdb8",
        "tertiary-fixed-dim": "#a6d700",
        "primary-container": "#1b3022",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5d6555",
        "on-secondary-fixed-variant": "#41493b",
        "tertiary-container": "#233000",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#161e11",
        "outline-variant": "#c3c8c1",
        "surface-tint": "#4d6453",
        "surface-container": "#eeeee9",
        "primary": "#061b0e",
        "secondary-fixed-dim": "#c1cab6",
        "on-surface-variant": "#434843",
        "on-tertiary": "#ffffff",
        "secondary-container": "#dae3cf",
        "tertiary": "#121a00",
        "surface-container-lowest": "#ffffff",
        "secondary": "#586151",
        "primary-fixed-dim": "#b4cdb8",
        "surface-container-low": "#f4f4ef",
        "secondary-fixed": "#dde6d2",
        "inverse-surface": "#2f312e",
        "background": "#fafaf5",
        "on-error": "#ffffff",
        "surface-container-high": "#e8e8e3",
        "error": "#ba1a1a",
        "tertiary-fixed": "#bef500",
        "on-primary": "#ffffff",
        "outline": "#737973"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
